# Configuració simple de Mimir per Docker
target: all
#
multitenancy_enabled: false
#
server:
  http_listen_port: 9009
  grpc_listen_port: 9095
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  log_level: info

## Configuració del storage de blocs
#blocks_storage:
#  backend: filesystem
#  filesystem:
#    dir: /data/blocks
#  tsdb:
#    dir: /data/tsdb
#
#distributor:
#  ring:
#    kvstore:
#      store: memberlist
#
#ingester:
#  ring:
#    kvstore:
#      store: memberlist
#    replication_factor: 1
#
#store_gateway:
#  sharding_ring:
#    replication_factor: 1
#
#compactor:
#  data_dir: /data/compactor
#  sharding_ring:
#    wait_stability_min_duration: 0s
#
#ruler:
#  rule_path: /data/ruler
#  ring:
#    kvstore:
#      store: memberlist
#
#alertmanager:
#  data_dir: /data/alertmanager
#  external_url: http://localhost:9009/alertmanager
#  sharding_ring:
#    replication_factor: 1
#
#memberlist:
#  abort_if_cluster_join_fails: false
#  bind_port: 7946
#
#limits:
#  ingestion_rate: 10000
#  ingestion_burst_size: 20000