version: '3.8'

services:
  k6:
    image: grafana/k6:1.0.0
    volumes:
      - ./app:/app # Munta el teu script de test
 
    environment:
      - 'K6_OUT=experimental-prometheus-rw'
      - 'K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write'
      - 'K6_PROMETHEUS_RW_TREND_STATS=p(90),p(95),avg,min,max'

    command: run /app/test.js
    # Recomanat si vols assegurar que l'API estigui en marxa abans que k6
    #depends_on:
    #  - contenidorapi
    #external_links:
    #  - reservesapi:contenidorapi
    networks:
      - internal # Connecta aquest servei a la xarxa existent

networks:
  internal:
    name: xarxa_docker1 # Aquest és el nom real de la xarxa que ja heu creat (amb `docker network create -d bridge xarxa_docker1`)
    external: true # Indica a Docker Compose que aquesta xarxa ja existeix i no ha de ser gestionada per ell

