version: '3.8'

services:
  # Grafana - La plataforma de visualització
  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      # Configuració opcional: pots canviar el password de l'admin inicial
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=1357924680
      # Si no els configures, l'usuari/password per defecte serà admin/admin
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    restart: unless-stopped
    networks:
      - monitoring_network

  # Loki - Sistema d'agregació de logs
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro
      - loki_data:/loki
    restart: unless-stopped
    networks:
      - monitoring_network

  # Grafana Alloy - Per enviar logs, mètriques i traces (successor de Grafana Agent)
  grafana-alloy: # Nom del servei canviat a 'grafana-alloy'
    image: grafana/alloy:v1.9.1 # Imatge i versió actualitzades a Grafana Alloy
    container_name: grafana-alloy
    ports:
      - "12345:12345" # Port per a l'API d'Alloy
    command: -config.file=/etc/alloy/config.alloy # Canvi de nom de la configuració (.alloy)
    volumes:
      - ./grafana-alloy/config.alloy:/etc/alloy/config.alloy:ro # Ruta de configuració ajustada
      - /var/log:/var/log:ro # Per recollir logs del host
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Per logs de Docker
    restart: unless-stopped
    networks:
      - monitoring_network

  # Mimir - Base de dades de sèries temporals escalable per a mètriques
  mimir:
    image: grafana/mimir:2.16.0
    container_name: mimir
    ports:
      - "9009:9009"
    command: -config.file=/etc/mimir/mimir.yaml
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir/mimir.yaml:ro
      - mimir_data:/data
    restart: unless-stopped
    networks:
      - monitoring_network

  # Tempo - Sistema d'agregació de traces
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "14268:14268" # Jaeger gRPC
      - "4317:4317" # OpenTelemetry gRPC
      - "4318:4318" # OpenTelemetry HTTP
      - "9411:9411" # Zipkin
      - "3200:3200" # HTTP
    command: -config.file=/etc/tempo/config.yaml
    volumes:
      - ./tempo/config.yaml:/etc/tempo/config.yaml:ro
      - tempo_data:/tmp/tempo
    restart: unless-stopped
    networks:
      - monitoring_network

networks:
  monitoring_network:
    name: xarxa_docker1 # Aquest és el nom real de la xarxa que ja heu creat (amb `docker network create -d bridge xarxa_docker1`)
    external: true # Indica a Docker Compose que aquesta xarxa ja existeix i no ha de ser gestionada per ell

volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/docker/grafana/grafana_data'
  loki_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/docker/grafana/loki_data'
  mimir_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/docker/grafana/mimir_data'
  tempo_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/docker/grafana/tempo_data'