server:
  http_listen_port: 3200
  grpc_listen_port: 9096
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0

# Configuració de recepció de traces
distributor:
  receivers:
    # OpenTelemetry
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    # Jaeger
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
          endpoint: 0.0.0.0:14268
        thrift_compact:
          endpoint: 0.0.0.0:6831
        thrift_binary:
          endpoint: 0.0.0.0:6832
    # Zipkin
    zipkin:
      endpoint: 0.0.0.0:9411

# Ingester - processa i emmagatzema traces
ingester:
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

# Emmagatzematge local
storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

# Compactor - compacta i manté blocs de traces
compactor:
  compaction:
    compaction_window: 1h
    max_compaction_objects: 1000000
    block_retention: 1h
    compacted_block_retention: 10m

# Query Frontend - optimitza consultes de traces
query_frontend:
  search:
    max_duration: 0s
  trace_by_id:
    query_timeout: 10s

# Configuració de mètriques generades a partir de traces
metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://mimir:9009/api/v1/push
        send_exemplars: true

# Límits i configuració de rendiment
limits:
  # Límits per trace
  max_traces_per_user: 10000
  max_bytes_per_trace: 5000000
  
  # Límits de cerca
  max_search_bytes_per_trace: 0
  max_search_duration: 0s
  
  # Límits de consulta
  max_bytes_per_tag_values_query: 5000000

# Configuració de cerca i indexació
search:
  default_result_limit: 20
  max_result_limit: 0
  max_duration: 0s

# Configuració per a Service Graph
service_graphs:
  max_items: 10000
  wait: 3s
  workers: 10