version: '3.8'

services:
  telegraf:
    image: telegraf:1.34.4-alpine
    container_name: telegraf
    restart: unless-stopped
    volumes:
      # Muntar el fitxer de configuració de Telegraf
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      # Muntar les rutes del host que Telegraf necessita
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
      # - /var:/hostfs/var:ro # Si necessites més mètriques
    environment:
      # Variables d'entorn per indicar a Telegraf on trobar els fitxers del host
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_REAL_HOSTNAME=${HOSTNAME} # O el nom que vulguis per al host
    networks:
      - internal # Connecta Telegraf a la xarxa externa

networks:
  internal:
    name: xarxa_docker1 # El nom de la xarxa que ja has creat i on InfluxDB està connectat
    external: true # Indica a Docker Compose que aquesta xarxa ja existeix
